name: "On Pull Request"

on:
  workflow_dispatch
  #push:
    #branches:
      #- master
      #- develop

jobs:
  install:
      name: Install npm and Cypress
      runs-on: ubuntu-22.04
      steps:
        - uses: actions/checkout@v4
  
        # install a specific version of Node using
        # https://github.com/actions/setup-node
        - name: Use Node.js 20
          uses: actions/setup-node@v4
          with:
            node-version: 20
            
        # Starts local server, then runs Cypress tests and records results on Cypress Cloud
        - name: Cypress tests
          run: |
            npm start &
            npx cypress run --record --parallel --group "Parallel 2x"
