name: "On Merge"

on:
  workflow_dispatch
  #push:
    #branches:
      #- master
      #- develop

jobs:
  basic-ubuntu-20:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress tests        
        uses: cypress-io/github-action@v6
        with:          
          build: npm run build
          start: npm start
  
