name: "On Pull Request"

on:
  push:
    branches:
      - master
      - develop

jobs:
  install:
      name: Install npm and Cypress
      runs-on: ubuntu-22.04
      steps:
        - uses: actions/checkout@v4
  
        # install a specific version of Node using
        # https://github.com/actions/setup-node
        - name: Use Node.js 20
          uses: actions/setup-node@v4
          with:
            node-version: 20
