name: "On Pull Request"

on:
  workflow_dispatch
  #push:
    #branches:
      #- master
      #- develop

jobs:
  basic-ubuntu-20:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress tests
        # normally you would write
        # uses: cypress-io/github-action@v6
        uses: ./
        # the parameters below are only necessary
        # because we are running these examples in a monorepo
        with:
          working-directory: examples/basic
          # just for full picture after installing Cypress
          # print information about detected browsers, etc
          # see https://on.cypress.io/command-line#cypress-info
          build: npx cypress info
  
